### ISSUE TITLE
I keep get that error

### ISSUE THREAD

**Issue by Gamaleldientarek** [IsaacTay/Flow.Launcher.Plugin.FendCalculator#1]
Error
fend command error- Check installation path or fend config file

I Installed fend from the Plugins in flow launcher, but I keep getting the same issue 

@IsaacTay

**Comment by Gamaleldientarek** [comment]
![image](https://user-images.githubusercontent.com/59454675/235388451-15f1bc5d-d735-4b0c-bff3-5ea01f4ee8d9.png)
@IsaacTay

**Comment by IsaacTay** [comment]
Hi, fend is separate program that this plugin interfaces with. Currently this plugin doesn't install `fend` automatically, but it will be added in the future.

For now, you can install fend through [scoop](https://scoop.sh/#/apps?id=e6f0a9d6e20f46ef6481143944e6bb44fb766fb4), [chocolatey](https://community.chocolatey.org/packages/fend), [winget](https://printfn.github.io/fend/documentation/#installation), the [official msi installer](https://github.com/printfn/fend/releases/latest/download/fend-windows-x64.msi), or  as a [standalone binary](https://github.com/printfn/fend/releases/tag/v1.1.6).

I hope this fixes your issue!

**Comment by Gamaleldientarek** [comment]
Thank you for answering me

I did install fend, remove the Fend plugin from flow, and reinstalled it... but unfortunately, I keep getting the same error

**Comment by FractalGeodes** [comment]
We were having this issue, I fixed it by changing the fend path config to fend's file location (`"C:\Program Files\fend\bin\fend.exe"` for us) and now it works

**Comment by IsaacTay** [comment]
Ah okay I see the problem. I mistakenly assumed that the fend program files were added to the system `PATH` by default, I am working on a fix right now so you won't have to manually configure it to point to the `fend.exe`. In the case that your fend installation isn't at Program Files, you can also do what @Ringlings said and configure it in the plugin config here: 

![image](https://user-images.githubusercontent.com/8254110/235579372-22d7f499-5c1d-43d6-969d-9e3450e1f81b.png)

**Comment by IsaacTay** [comment]
I've added the support to automatically detect fend if it is located in the program files, and also a reset button that'll trigger the auto-detect. This should fix the problem, if not, feel free to open the issue again
