### ISSUE TITLE
Option for timeout

### ISSUE THREAD

**Issue by RagibHasin** [IsaacTay/Flow.Launcher.Plugin.FendCalculator#3]
Many innocuous queries (e.g. `e^e`) can take a long time to finish, invoking a background task that continues running even after the user has closed the query.

A configurable timeout would be very useful in this case.

**Comment by IsaacTay** [comment]
That sounds like a good idea, I'll implement that soon

**Comment by TheSketty** [comment]
After timeout, process still doesn't close
<img width="645" height="191" alt="Image" src="https://github.com/user-attachments/assets/8025c7bd-e17a-489f-913c-207003a26855" />
